# Generated by Django 2.2.2 on 2019-06-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restraunts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(max_length=100)),
                ('res_image', models.ImageField(upload_to='images')),
                ('contact_no', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name_plural': "Restraunt's Infos",
            },
        ),
    ]
