# Generated by Django 2.2.2 on 2019-06-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restraunts',
            new_name='Restaurants',
        ),
    ]
