# Generated by Django 2.2.2 on 2019-06-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_auto_20190605_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.PositiveIntegerField()),
                ('x', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name_plural': 'Delivery partners',
            },
        ),
    ]
