# Generated by Django 2.2.2 on 2019-06-05 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='images')),
                ('contact_no', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('x', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('y', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
